### PR TITLE
Update data file locations for build 11

### PR DESCRIPTION
**Pull request by sosey**
Script is updated to point to the data for build 11

### CODE REVIEW

**Review by zacharyburnett — APPROVED** [review]
LGTM, if the notebooks run!

**Comment by sosey** [comment]
@zacharyburnett dont quite merge yet....

**Comment by nden** [comment]
We need to send files that match Build12. 
A Level 2 imaging file matching the Build 12  release is in ExampleData. A grism Level 2 file matching Build 12 is in ExampleData/grsim_data (may have the name wrong).

Recently there was interest only in getting the Level 2 files so when I uploaded them I did not upload a L1 file and did not update the notebooks. If this is needed, a L1 file needs to be uploaded to Box and the notebooks updated. Perhaps @WilliamJamieson can help with this.

**Comment by sosey** [comment]
@ddavis-stsci generated new files for me. It took a while to upload, but I  tested the download successfully. When the tests pass here we should be good to merge @zacharyburnett

**Pull request merged**
