### PR TITLE
Add notebook example of JWST NIRISS grism processing

### PR DESCRIPTION
**Pull request by nden**
This was presented at a `Data Formats Meeting` on Sep 6th.

### CODE REVIEW

**Comment by sosey** [comment]
<p>I think the notebook itself looks good - do you want to clean the executed cells before merging? This usu helps with diffs later too.</p>

**Review by sosey — APPROVED** [review]
The notebook and data inclusions look good to me. Considering cleaning the noteobook output cells before merging the PR?

**Comment by WilliamJamieson** [comment]
@sosey

> The notebook and data inclusions look good to me. Considering cleaning the noteobook output cells before merging the PR?

Should I open a PR to setup a pre-commit hook and some CI to enforce this. Like the Scipy Tutorial's notebooks e.g. [this](https://github.com/asdf-format/scipy2022tutorial/blob/9ca0e2561816b5a1e08a0a4f5e5c941ad2569be0/.pre-commit-config.yaml#L14-L17) part forces notebooks to strip their outputs.

**Comment by nden** [comment]
@WilliamJamieson jwst is now included in the environment, the failure comes from CRDS. Not sure what we can do about this in the automated test. I included a note about setting CRDS in the notebook, perhaps that's sufficient.

I'd like to keep the outputs for this particular notebook because I can see some not wanting to run it but still interested in following the workflow and looking at the results.

**Review by WilliamJamieson — APPROVED** [review]

**Pull request merged**
